// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package view_blog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/harrisbisset/blog/models"
import "github.com/harrisbisset/blog/render/views/view_layout"

func BlogPost(p models.Post) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"pr-[15px] max-w-[900px]\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = BlogStyle().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = models.GetContent(p).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = view_layout.Main().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func BlogStyle() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `
        h1 {
            color: #d164a9;
            font-size: 2.25rem;
            line-height: 3rem;
            width: 90%;
        }

        h2 {
            color: #4b4599;
            font-size: 2rem;
            line-height: 2.5rem;
        }

        h1, h2 {
            margin-top: 10px;
            margin-bottom: 7px;
        }

        h3 {
            color: #7600d7;
            font-size: 1.5rem;
            line-height: 2rem;
        }

        h4 {
            color: #7600d7;
            font-size: 1.25rem;
            line-height: 1.7rem;
        }

        h1, h2, h3, h4 {
            font-weight: 600;
        }

        p, li {
            font-family: "Open Sans";
            margin-top: 2px;
            margin-bottom: 2px;
        }

        blockquote {
            width: 90%;
            background-color: #eee8f4;
            padding: 0px;
        }

        blockquote ~ blockquote {
            width: 100%;
            background-color: #eee8f4;
            padding: 0px;
        }


        p {
            padding: 8px;
        }

        p, li {
            padding: 5px;
            color: #0f172a;
            line-height: 1.4;
            text-align: left;
        }

        ul, ol {
            padding-left: 45px;
        }

        ul {
            list-style-type: disc;
        }

        ol {
            list-style-type: decimal;
        }

        hr {
            border-color: #1e293b;
        }

        code {
            display: block;
            background-color: #fbf2fe;
            border-radius: 25px;
            padding-top: 5px;
            padding-right: 5px;
            padding-bottom: 5px;
            padding-left: 12px;
            border-left-width: 15px;
            border-left-color: #dedddd;
            overflow-x: scroll;
            width: 100%;
        }

        em {
            padding-right: 2px;
        }

        @media (prefers-color-scheme: dark) {

            h2 {
                color: #4477CE;
            }

            h3 {
                color: #a687c0;
            }

            h4 {
                color: #a687c0;
            }

            p {
                padding: 8px;
            }

            p, li {
                color: white;
            }

            blockquote {
                width: 90%;
                background-color: #0f172a;
            }

            blockquote ~ blockquote {
                width: 100%;
                background-color: #0f172a;
            }

            hr {
                border-color: black;
            }

            code {
                color: #71b6d7;
                background-color: #222832;
                border-left-color: #171c24;
            }
        }
    `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
